const assert = require('node:assert/strict');
const vm = require('node:vm');
const fs = require('node:fs');
const m = vm.createContext({});
vm.runInContext(fs.readFileSync('Model.js', 'utf8'), m);
const now = Date.parse('2026-09-11T00:00:00Z');
const record = m.parse({schemaVersion:1,id:'claude', limits:[{label:'Session (5-hour)',percent:.55}, {label:'Weekly (7-day)',percent:.8}, {label:'Bad',percent:null}, {label:'NaN',percent:NaN}]},'claude');
assert.equal(record.limits.length,2);
assert.equal(record.limits[0].title,'Session');
assert.equal(m.lead(record).percent,.8);
assert.equal(m.percent(.55,'Left'),'45%');
assert.equal(m.metrics(record,'Weekly (7-day)').length,1);
assert.equal(m.metrics(record,'Session (5-hour)').length,2);
record.limits[0].percent=.9;
assert.equal(m.lead(record).title,'Session');
assert.equal(m.metrics(record,'Session (5-hour)').length,1);
assert.equal(m.parse('{bad','claude'),null);
assert.equal(m.parse({schemaVersion:1,id:'codex',limits:[]},'claude'),null);
assert.equal(m.barLabel(m.providers[0],null,null,'Used'),'');
assert.equal(m.percents(record,'Weekly (7-day)','Used'),'90% · 80%');
assert.equal(m.percents(null,null,'Used'),'');
assert.equal(m.ordered(['grok','claude']).map(p => p.id).join(','), 'grok,claude,codex,cursor,opencode');
assert.equal(m.move(['grok','claude'],'claude',-1).join(','), 'claude,grok,codex,cursor,opencode');
assert.equal(m.move(['claude'],'claude',-1).join(','), 'claude,codex,cursor,opencode,grok');
assert.equal(m.pace({label:'Session (5-hour)',percent:.6,resetsAt:new Date(now+2.5*3600000).toISOString()},now),'alarm');
assert.equal(m.pace({label:'Weekly',percent:.9,resetsAt:''},now),'alarm');
assert.equal(m.pace({label:'Weekly',percent:.1,resetsAt:new Date(now+86400000).toISOString()},now),'ok');
assert.equal(m.countdown('invalid',now),'Reset unknown');
assert.equal(m.countdown(new Date(now-1).toISOString(),now),'Reset due');
console.log('Model tests passed');
